---
- hosts: ml
  tasks:

  - name: installing epel-release
    yum: name=epel-release state=present
    sudo: yes

  - name: installing python3.4
    yum: name=python34 state=latest
    sudo: yes

  - name: installing python3.4 setuptools
    yum: name=python34-setuptools state=present
    sudo: yes

  - name: installing pip3
    shell: easy_install-3.4 pip
    sudo: yes

  - name: installing Numpy
    shell: pip3 install numpy
    sudo: yes

  - name: installing Pandas
    shell: pip3 install pandas
    sudo: yes

  - name: installing Scikit-Learn
    shell: pip3 install scikit-learn
    sudo: yes

  - name: installing pandas-datareader
    shell: pip3 install pandas-datareader
    sudo: yes

  - name: installing web application framework (Flask)
    shell: pip3 install flask
    sudo: yes

  - name: installing form handler wtforms
    shell: pip3 install wtforms
    sudo: yes

  - name: installing SciPy
    shell: pip3 install scipy
    sudo: yes

  - name: installing git
    yum: name=git state=present
    sudo: yes

  - name: installing matplotlib dependencies
    yum: name={{ item }} state=present
    with_items:
      - gcc
      - "gcc-c++"
      - python-devel
      - make
      - gcc-gfortran
      - atlas
      - atlas-devel
      - lapack-devel
      - blas-devel
      - libpng-devel
      - freetype-devel
    sudo: yes

  - name: installing matplotlib
    yum: name={{ item }} state=present
    with_items:
      - python-matplotlib
    sudo: yes